name: Test, Build, and Deploy | Modul 01 - Lab 2.2 Senior Project 

on:
  push:
    branches: [main]

jobs:
  test-build: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Testing Build
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm i
      - run: npm run build

  deploy:
    needs: test-build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Deploy and Build on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/ ssh-praktikan9
            echo "Cek folder project";
            [ ! -d "${HOME}/senpro/497708/modul02/senpro-modul2-lab22-githubaction" ] && 
            {
              echo "Repository belum di-clone. Cloning...";
              mkdir -p ~/senpro/497708/modul02;
              cd ~/senpro/497708/modul02;
              git clone https://github.com/fahrinulyanisrina/senpro-modul2-lab22-githubaction.git;
              cd ~/senpro-modul2-lab22-githubaction;
              echo "Install package dan build project";
              npm install;
              npm run build;
            } || 
            {
              echo "Repository sudah ada. Building...";
              cd ~/senpro/497708/modul02/senpro-modul2-lab22-githubaction;
              git restore .;
              git pull origin main;
              echo "Install package dan build project";
              npm install;
              npm run build;
            }